# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-23 09:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('serves', models.IntegerField()),
                ('scalable', models.BooleanField(default=True)),
                ('prep_time', models.IntegerField(verbose_name='Prep Min')),
                ('cook_time', models.IntegerField(verbose_name='Cook Min')),
                ('description', models.TextField(max_length=4000)),
                ('ingredients', models.TextField(max_length=1500)),
                ('method', models.TextField(max_length=15000)),
                ('publisher', models.CharField(choices=[('MAGAZINE', 'MAGAZINE'), ('NEWSPAPER', 'NEWSPAPER'), ('WEBSITE', 'WEBSITE'), ('BOOK', 'BOOK'), ('SOCIAL CLUB', 'SOCIAL CLUB'), ('PROFESSIONAL', 'PROFESSIONAL')], max_length=20, verbose_name='publisher')),
                ('allergy', models.CharField(choices=[('NONE', 'NONE'), ('MILK', 'MILK'), ('EGG', 'EGG'), ('NUT', 'NUT'), ('SOYA', 'SOYA'), ('WHEAT', 'WHEAT'), ('FISH', 'FISH'), ('PORK', 'PORK')], max_length=20, verbose_name='allergy')),
                ('difficulty', models.CharField(choices=[('EASY', 'EASY'), ('NORM', 'NORMAL'), ('HARD', 'HARD'), ('EXPERT', 'EXPERT')], max_length=10, verbose_name='difficulty')),
                ('recipe_type', models.CharField(choices=[('BREAKFAST', 'BREAKFAST'), ('LUNCH', 'LUNCH'), ('DINNER', 'DINNER'), ('STARTER', 'STARTER'), ('DESSERT', 'DESSERT'), ('BRUNCH', 'BRUNCH'), ('SNACK', 'SNACK'), ('MAIN', 'MAIN COURSE'), ('SIDE', 'SIDE DISH'), ('DRINK', 'DRINK'), ('COCKTAIL', 'COCKTAIL'), ('CANAPE', 'CANAPE')], max_length=20, verbose_name='recipe Type')),
                ('cuisine', models.CharField(choices=[('AFRICAN', 'AFRICAN'), ('AMERICAN', 'AMERICAN'), ('ASIAN', 'ASIAN'), ('AUSTRALIAN', 'AUSTRALIAN'), ('CARIBBEAN', 'CARIBBEAN'), ('EUROPEAN', 'EUROPEAN'), ('MEDITERRANEAN', 'MEDITERRANEAN')], max_length=20, verbose_name='cuisine')),
                ('uploaded_date', models.DateField(auto_now_add=True, verbose_name='Date Uploaded')),
                ('updated', models.DateField(auto_now=True, verbose_name='Last Updated')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('notes', models.TextField(blank=True, max_length=1500)),
                ('country', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'recipe',
                'verbose_name_plural': 'recipes',
            },
        ),
    ]
